### ISSUE TITLE
'CustomDatepickerI18n' does not implement inherited abstract member 'getDayAriaLabel' from class 'NgbDatepickerI18n'

### ISSUE THREAD

**Issue by mrjohnr** [ng-bootstrap/ng-bootstrap#2362]
Hi,After upgrading from v1.1.1 to 2.0.0  I've got this error 

> 'CustomDatepickerI18n' does not implement inherited abstract member 'getDayAriaLabel' from class 'NgbDatepickerI18n'

on  a custom control:
```
....
@Injectable()
export class CustomDatepickerI18n extends NgbDatepickerI18n {

  constructor(private _i18n: I18n) {
    super();
  }
........
```

thanks

**Comment by pkozlowski-opensource** [comment]
It is part of the breaking changes for 2.0.0, see https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#breaking-changes

**Comment by mrjohnr** [comment]
Thanks solved:
```
 getDayAriaLabel(date: NgbDateStruct): string {
    return `${date.day}-${date.month}-${date.year}`;
  }
```
what about autoclose  Datepicker popup when is closed outside:   https://github.com/ng-bootstrap/ng-bootstrap/issues/783
