### ISSUE TITLE
ng-bootstrap not working with Angular 5 / Cli 1.5.0.

### ISSUE THREAD

**Issue by mhosman** [ng-bootstrap/ng-bootstrap#1952]
I just made all imports correctly and I get:

Error: StaticInjectorError[NgbDropdown]: 
  StaticInjectorError[NgbDropdown]: 
    NullInjectorError: No provider for NgbDropdown!

**Comment by maxokorokov** [comment]
There is no official Angular 5 support yet. However it works fine for me on a default CLI `1.5.0`project with the only `NgbMobule.forRoot()` import

**Comment by mhosman** [comment]
In my case I just made that import in the app.module.ts but is not working in other modules.

**Comment by mhosman** [comment]
In app.module.ts:

import { NgbModule } from '@ng-bootstrap/ng-bootstrap';

imports: [
   NgbModule.forRoot()
]

If I try to add a ngbDropdownToggle in the html of other module I just get that message.

**Comment by maxokorokov** [comment]
You're most likely missing `import: [NgbModule]` in other modules or something like that.

And I'm sorry, but:
- this is a support request and as such doesn't belong here: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
- we can't help much without a reproduce scenario

**Comment by samarahmad** [comment]
i m also getting same error 
how can i fix??

**Comment by delacruzjames** [comment]
Me too I'm also getting same error
* Steps
angular 5.2.5
bootstrap 4
npm install --save @ng-bootstrap/ng-bootstrap

import { NgbModule } from '@ng-bootstrap/ng-bootstrap'; # include to app.module.ts 
error "cannot find module @ng-bootstrap/ng-bootstrap'

**Comment by wangjia184** [comment]
same issue here

**Comment by maxokorokov** [comment]
@delacruzjames, @wangjia184, @samarahmad that's not helping

- check [installation instructions](https://ng-bootstrap.github.io/#/getting-started)
- check this StackBlitz for [minimal angular cli setup](https://stackblitz.com/edit/ng-bootstrap-minimal)
- if you believe that we've got a bug in this library than please provide a minimal reproduce scenario in a plunker: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug
- if you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

**Comment by vimalan-sakthivel** [comment]
CSS is not getting applied.

**Comment by gisterpages** [comment]
Hi All,

Please view the screenshot below:
http://prntscr.com/j0xo4x

Just add the code in
.angular-cli.json

Doing so will add the css throughout the app.

I got it resolved the other day I posted in here, but missed to update an answer.

Glad that @vimalan-sakthivel commented and I received a mail about it.
Thanks.

**Comment by raDiesle** [comment]
Same here with angular 6. Browser crashing in infinite loop.
Error: StaticInjectorError(AppModule)[NgbDropdownMenu -> NgbDropdown]: 
  StaticInjectorError(Platform: core)[NgbDropdownMenu -> NgbDropdown]: 
    NullInjectorError: No provider for NgbDropdown!

**Comment by TommyJackson85** [comment]
How did you fix it raDiesle? I am getting the same error with ngbPopover  ...
StaticInjectorError(Platform: core)[NgbPopover -> NgbPopoverConfig]:
