### ISSUE TITLE
ngbootstrap/ngbootstrap issue

### ISSUE THREAD

**Issue by ankitkm418** [ng-bootstrap/ng-bootstrap#3679]
ERROR in node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.d.ts(192,9): error TS1086: An accessor cannot be 
declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/buttons/checkbox.d.ts(29,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/buttons/radio.d.ts(14,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/buttons/radio.d.ts(15,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/buttons/radio.d.ts(62,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/buttons/radio.d.ts(66,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/buttons/radio.d.ts(67,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/buttons/radio.d.ts(68,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/buttons/radio.d.ts(69,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/buttons/radio.d.ts(70,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/buttons/radio.d.ts(71,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/carousel/carousel.d.ts(42,9): error TS1086: An accessor cannot be declared in 
an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/carousel/carousel.d.ts(43,9): error TS1086: An accessor cannot be declared in 
an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/carousel/carousel.d.ts(47,9): error TS1086: An accessor cannot be declared in 
an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/carousel/carousel.d.ts(48,9): error TS1086: An accessor cannot be declared in 
an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/carousel/carousel.d.ts(58,9): error TS1086: An accessor cannot be declared in 
an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/carousel/carousel.d.ts(59,9): error TS1086: An accessor cannot be declared in 
an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker-input.d.ts(204,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker-input.d.ts(205,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker-month.d.ts(26,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker-service.d.ts(16,9): error TS1086: An accessor cannot be 
declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker-service.d.ts(17,9): error TS1086: An accessor cannot be 
declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.d.ts(237,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.d.ts(243,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.d.ts(16,9): error TS1086: An accessor cannot be declared in 
an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.d.ts(17,9): error TS1086: An accessor cannot be declared in 
an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-ref.d.ts(40,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/nav/nav.d.ts(64,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/nav/nav.d.ts(65,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/nav/nav.d.ts(66,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/progressbar/progressbar.d.ts(12,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/progressbar/progressbar.d.ts(13,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/tabset/tabset.d.ts(93,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/timepicker/timepicker.d.ts(36,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/timepicker/timepicker.d.ts(37,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/timepicker/timepicker.d.ts(41,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/timepicker/timepicker.d.ts(42,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/timepicker/timepicker.d.ts(46,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/timepicker/timepicker.d.ts(47,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/timepicker/timepicker.d.ts(73,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/timepicker/timepicker.d.ts(74,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.d.ts(101,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.d.ts(102,9): error TS1086: An accessor cannot be declared in an ambient context.
    
after i use that model this issue come always, there is no error everything fine but it irritates me in terminal, How i solve this???

i have try all of that things that provide on stack over flow and github, but doesnt work anything?

**Comment by maxokorokov** [comment]
Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by ankitkm418** [comment]
ya if i install and use ngb module than throws that big error list that cant be resolved,
but the project is running

**Comment by gvlekke** [comment]
also got this when upgrading from angular 8 to angular 9, also got it with other libraries btw.

**Comment by benouat** [comment]
I suspect this is due to how Angular pre-process all the thing after `install` with v9.
We've seen that several time when migrating from v8 to v9.

A clean install (with removing `node_modules`) usually fix the bug.
Will close for now.
