### ISSUE TITLE
AOT Compilation Error with v2.2.1

### ISSUE THREAD

**Issue by omardoma** [ng-bootstrap/ng-bootstrap#2562]
### Bug description:

I am using ng-bootstrap for various parts of my app, since I upgraded to v2.2.1, I get a "cannot read property 'subscribe' of undefined".

I am sure its ng-bootstrap since I am using multiple libraries and I kept debugging and removing them one by one and trying to build with AOT until I found that it was ng-bootstrap, once I downgraded to v2.2.0, it worked normally.

Components I am using are buttons, dropdown, alert and tabs, however, I suspect its something with the dropdown since only the component I am using it in (Header) causes issues, the rest of the components work normally.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.1.0

ng-bootstrap: 2.2.1

Bootstrap: 4.1.3

**Comment by pkozlowski-opensource** [comment]
Could you please share a reproduce scenario (or a stack trace, as a very minimum...). Otherwise it is very hard to investigate and fix...

**Comment by omardoma** [comment]
There is no real reproduce scenario as it is with minimal usage of ng-bootstrap and running ng build --prod, however here is a screenshot of the error.
<img width="635" alt="screen shot 2018-08-02 at 12 03 25 pm" src="https://user-images.githubusercontent.com/25301162/43577520-5804d9c0-964c-11e8-9779-5cc58fab52e8.png">

**Comment by omardoma** [comment]
On a side note, running ng build --prod --aot=false --build-optimizer=false, works correctly, so its an issue with AOT for sure

**Comment by pkozlowski-opensource** [comment]
@omardoma could you please try with `ng build --prod --aot=true --build-optimizer=false`. Also, what is the CLI version that you are using? 

I'm kind of curious what is going on here as we don't hear more reports of this error despite having ~50k downloads per day...

**Comment by omardoma** [comment]
CLI Version: 6.1.1

**Comment by maxokorokov** [comment]
Also which `rxjs` version you're using? `package.json` might be helpful, because I don't have any issues with clean cli install and a dropdown.

Also try cleaning npm cache, removing node modules, etc

**Comment by maxokorokov** [comment]
it seems like we have `race(...).subscribe()` in the dropdown that wasn't there in `2.2.0`, so looks like some kind of caching issue to me

**Comment by omardoma** [comment]
@maxokorokov Actually I followed your suggestion of clearing npm cache and deleteing node_modules and now it works, so you are right.

Thanks a lot, I am closing the issue now.
